app = "found-haikus"
primary_region = "ewr"

[build]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 2

[env]
  FEEDGEN_DB_PATH = "/data/haiku.db"

[mounts]
  source = "haiku_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    path = "/.well-known/did.json"
